# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jjsu/SciComp/LEND/2016LEND/CSETNTracking/codeC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jjsu/SciComp/LEND/2016LEND/CSETNTracking/codeC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jjsu/SciComp/LEND/2016LEND/CSETNTracking/codeC/CMakeFiles /Users/jjsu/SciComp/LEND/2016LEND/CSETNTracking/codeC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jjsu/SciComp/LEND/2016LEND/CSETNTracking/codeC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DOWSER01

# Build rule for target.
DOWSER01: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DOWSER01
.PHONY : DOWSER01

# fast build rule for target.
DOWSER01/fast:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/build
.PHONY : DOWSER01/fast

DOWSER01.o: DOWSER01.cc.o

.PHONY : DOWSER01.o

# target to build an object file
DOWSER01.cc.o:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/DOWSER01.cc.o
.PHONY : DOWSER01.cc.o

DOWSER01.i: DOWSER01.cc.i

.PHONY : DOWSER01.i

# target to preprocess a source file
DOWSER01.cc.i:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/DOWSER01.cc.i
.PHONY : DOWSER01.cc.i

DOWSER01.s: DOWSER01.cc.s

.PHONY : DOWSER01.s

# target to generate assembly for a file
DOWSER01.cc.s:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/DOWSER01.cc.s
.PHONY : DOWSER01.cc.s

src/DOWSER01DetectorConstruction.o: src/DOWSER01DetectorConstruction.cc.o

.PHONY : src/DOWSER01DetectorConstruction.o

# target to build an object file
src/DOWSER01DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01DetectorConstruction.cc.o
.PHONY : src/DOWSER01DetectorConstruction.cc.o

src/DOWSER01DetectorConstruction.i: src/DOWSER01DetectorConstruction.cc.i

.PHONY : src/DOWSER01DetectorConstruction.i

# target to preprocess a source file
src/DOWSER01DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01DetectorConstruction.cc.i
.PHONY : src/DOWSER01DetectorConstruction.cc.i

src/DOWSER01DetectorConstruction.s: src/DOWSER01DetectorConstruction.cc.s

.PHONY : src/DOWSER01DetectorConstruction.s

# target to generate assembly for a file
src/DOWSER01DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01DetectorConstruction.cc.s
.PHONY : src/DOWSER01DetectorConstruction.cc.s

src/DOWSER01EventAction.o: src/DOWSER01EventAction.cc.o

.PHONY : src/DOWSER01EventAction.o

# target to build an object file
src/DOWSER01EventAction.cc.o:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01EventAction.cc.o
.PHONY : src/DOWSER01EventAction.cc.o

src/DOWSER01EventAction.i: src/DOWSER01EventAction.cc.i

.PHONY : src/DOWSER01EventAction.i

# target to preprocess a source file
src/DOWSER01EventAction.cc.i:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01EventAction.cc.i
.PHONY : src/DOWSER01EventAction.cc.i

src/DOWSER01EventAction.s: src/DOWSER01EventAction.cc.s

.PHONY : src/DOWSER01EventAction.s

# target to generate assembly for a file
src/DOWSER01EventAction.cc.s:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01EventAction.cc.s
.PHONY : src/DOWSER01EventAction.cc.s

src/DOWSER01PrimaryGeneratorAction.o: src/DOWSER01PrimaryGeneratorAction.cc.o

.PHONY : src/DOWSER01PrimaryGeneratorAction.o

# target to build an object file
src/DOWSER01PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01PrimaryGeneratorAction.cc.o
.PHONY : src/DOWSER01PrimaryGeneratorAction.cc.o

src/DOWSER01PrimaryGeneratorAction.i: src/DOWSER01PrimaryGeneratorAction.cc.i

.PHONY : src/DOWSER01PrimaryGeneratorAction.i

# target to preprocess a source file
src/DOWSER01PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01PrimaryGeneratorAction.cc.i
.PHONY : src/DOWSER01PrimaryGeneratorAction.cc.i

src/DOWSER01PrimaryGeneratorAction.s: src/DOWSER01PrimaryGeneratorAction.cc.s

.PHONY : src/DOWSER01PrimaryGeneratorAction.s

# target to generate assembly for a file
src/DOWSER01PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01PrimaryGeneratorAction.cc.s
.PHONY : src/DOWSER01PrimaryGeneratorAction.cc.s

src/DOWSER01RunAction.o: src/DOWSER01RunAction.cc.o

.PHONY : src/DOWSER01RunAction.o

# target to build an object file
src/DOWSER01RunAction.cc.o:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01RunAction.cc.o
.PHONY : src/DOWSER01RunAction.cc.o

src/DOWSER01RunAction.i: src/DOWSER01RunAction.cc.i

.PHONY : src/DOWSER01RunAction.i

# target to preprocess a source file
src/DOWSER01RunAction.cc.i:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01RunAction.cc.i
.PHONY : src/DOWSER01RunAction.cc.i

src/DOWSER01RunAction.s: src/DOWSER01RunAction.cc.s

.PHONY : src/DOWSER01RunAction.s

# target to generate assembly for a file
src/DOWSER01RunAction.cc.s:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01RunAction.cc.s
.PHONY : src/DOWSER01RunAction.cc.s

src/DOWSER01SteppingAction.o: src/DOWSER01SteppingAction.cc.o

.PHONY : src/DOWSER01SteppingAction.o

# target to build an object file
src/DOWSER01SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01SteppingAction.cc.o
.PHONY : src/DOWSER01SteppingAction.cc.o

src/DOWSER01SteppingAction.i: src/DOWSER01SteppingAction.cc.i

.PHONY : src/DOWSER01SteppingAction.i

# target to preprocess a source file
src/DOWSER01SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01SteppingAction.cc.i
.PHONY : src/DOWSER01SteppingAction.cc.i

src/DOWSER01SteppingAction.s: src/DOWSER01SteppingAction.cc.s

.PHONY : src/DOWSER01SteppingAction.s

# target to generate assembly for a file
src/DOWSER01SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/DOWSER01.dir/build.make CMakeFiles/DOWSER01.dir/src/DOWSER01SteppingAction.cc.s
.PHONY : src/DOWSER01SteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... DOWSER01"
	@echo "... install"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... DOWSER01.o"
	@echo "... DOWSER01.i"
	@echo "... DOWSER01.s"
	@echo "... src/DOWSER01DetectorConstruction.o"
	@echo "... src/DOWSER01DetectorConstruction.i"
	@echo "... src/DOWSER01DetectorConstruction.s"
	@echo "... src/DOWSER01EventAction.o"
	@echo "... src/DOWSER01EventAction.i"
	@echo "... src/DOWSER01EventAction.s"
	@echo "... src/DOWSER01PrimaryGeneratorAction.o"
	@echo "... src/DOWSER01PrimaryGeneratorAction.i"
	@echo "... src/DOWSER01PrimaryGeneratorAction.s"
	@echo "... src/DOWSER01RunAction.o"
	@echo "... src/DOWSER01RunAction.i"
	@echo "... src/DOWSER01RunAction.s"
	@echo "... src/DOWSER01SteppingAction.o"
	@echo "... src/DOWSER01SteppingAction.i"
	@echo "... src/DOWSER01SteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

